# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_energy <- function(x) {
    .Call(`_wearableAnomaly_pairwise_energy`, x)
}

energy_stat_segment <- function(x, a, b, c, d) {
    .Call(`_wearableAnomaly_energy_stat_segment`, x, a, b, c, d)
}

pelt_core_meanvar <- function(x, min_seg_len, pen_value) {
    .Call(`_wearableAnomaly_pelt_core_meanvar`, x, min_seg_len, pen_value)
}

